name: directed-keys
version: 0.4.0
ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -fno-warn-warnings-deprecations
dependencies:
- base
- base64-bytestring
- bytestring
- cereal
- compressed
- containers
- hashable
- zlib
library:
  source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - directed-keys
    - hspec
    - QuickCheck
    - serial-test-generators
